music_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new, :index]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
  
end

music_project/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  yr         :integer          not null
#  live_album :boolean          default(FALSE)
#

class Album < ApplicationRecord

    validates :title, :yr, presence: true

    belongs_to :band,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: 'Band'
        
end

music_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_project/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: 'Album'
        
end

music_project/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

#FIGVAPER
# find_by_credentials
# is_password?
# generate_session_token
# validations
# after_initialize
# password=()
# ensure_session_token
# reset_session_token!

class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }

    after_initialize :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        user && user.is_password?(password) ? user : nil
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

    def reset_session_token!
        self.update!(session_token: self.class.generate_session_token)
        self.session_token
    end
end

music_project/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    
    def index
        @band = Band.find(params[:band_id])
        @albums = @band.albums
        render :index
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def new
        @album = Album.new
        @bands = Band.all
        render :new
    end

    def edit
        @album = Album.find(params[:id])
        render :edit
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    def update
        @album = Album.find(params[:id])
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        render :index
    end

    def album_params
        params.require(:album).permit(:title, :yr, :band_id)
    end

end

music_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by_session_token(session[:session_token])
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logged_in?
        !!self.current_user
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
    end

    def require_logged_in!
        redirect_to new_session_url unless logged_in?
    end

    def require_no_user!
        redirect_to bands_url if current_user
    end

end

music_project/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    
    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def update
        @band = Band.find(params[:id])
        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        render :index
    end

    def band_params
        params.require(:band).permit(:name)
    end


end

music_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            login(user)
            redirect_to bands_url
        else
            flash.now[:errors] = ["Invalid Email or Password"]
            render :new
        end
    end

    def destroy
        if current_user
            current_user.reset_session_token!
            session[:session_token] = nil
            @current_user = nil
            redirect_to new_session_url
        end
    end

end

music_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to bands_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        if @user
            render json: @user.email
            ###redirect_to user_url
        else
            flash.now[:errors] = @user.errors.full_messages
            redirect_to bands_url
        end
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

music_project/app/helpers/application_helper.rb
module ApplicationHelper
end

music_project/app/views/albums/edit.html.erb
<h2>Edit this album</h2>

<form action="<%= album_url %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label for="band_name">Band Name</label>
        <input  type="text"
                name="album[band_id]"
                id="band_name"
                value="<%= @album.band.name %>">

    <input type="submit" value="Update Band">
</form>

music_project/app/views/albums/index.html.erb
<h2>All albums by <%= @band.name %></h2>

<ul>
<% @albums.each do |album| %>
    <% if album.band_id == @band.id %>
    <li>
    <%= album.title %>
    </li>
    <% end %>
<% end %>

</ul>

<a href="<%= new_band_album_url %>">Create a new Album</a>

music_project/app/views/albums/new.html.erb
<h2>Create a new album</h2>

<form action="<%= albums_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label for="album_title">Album Title</label>
        <input  type="text"
                name="album[title]"
                id="album_title"
                value="">

    <label for="album_year">Album Year</label>
        <input  type="text"
                name="album[yr]"
                id="album_year"
                value="">

    <label for="band_name">Created By:</label>
        <select name="album[band_id]" id="band_name">
        <option disabled selected>-- select a Band --</option>
        <% @bands.each do |band| %>
            <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
        </select>

    <input type="submit" value="Add this Album">
</form>

music_project/app/views/albums/show.html.erb
<h2>All about <%= @album.title %></h2>

Album Name: <%= @album.title %>
<br>
Written By: <%= @album.band.name %>
<br>
Year: <%= @album.yr %>
<p>
<a href="<%= bands_url %>">Take me back to BANDS!</a>
</p>

music_project/app/views/bands/edit.html.erb
<h2>Edit this band</h2>

<form action="<%= band_url %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label for="band_name">Band Name</label>
        <input  type="text"
                name="band[name]"
                id="band_name"
                value="<%= @band.name %>">

    <input type="submit" value="Update Band">
</form>

music_project/app/views/bands/index.html.erb
<h2>All the bands</h2>

<ul>
<% @bands.each do |band| %>
    <li>
    <%= band.name %>
    </li>
<% end %>
</ul>

<a href="<%= new_band_url %>">Create a new Band</a>

music_project/app/views/bands/new.html.erb
<h2>Create a new band!</h2>

<form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label for="band_name">Band Name</label>
        <input  type="text"
                name="band[name]"
                id="band_name"
                value="">

    <input type="submit" value="Create a Band">
</form>

music_project/app/views/bands/show.html.erb
<h2>All about <%= @band.name %></h2>

Band Name: <%= @band.name %>
<p>
<a href="<%= bands_url %>">Take me back to BANDS!</a>
</p>

music_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <h1>Music App (Stylish af)</h1>
    <br>
    <br>
    <% if logged_in? %>
      <h3>Welcome <%= current_user.email %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <input type="submit" value="LOGOUT">
      </form>
    <% else %>
      <div>
      <a href="<%= new_user_url %>" background-color="green" border-radius=5px>Sign Up!</a>
      <a href="<%= new_session_url %>">Log In</a>
      </div>
    <% end %>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

music_project/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

music_project/app/views/users/new.html.erb
<h2>Sign Up New User</h2>
<br><br>

<%= render 'shared/errors' %>

<form action="<%= users_url %>" method="POST">
    <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

    <label for="email">Email</label>
        <input
            type="text"
            name="user[email]"
            id="email"
            value="">

    <label for="password">Password</label>
        <input
            type="password"
            name="user[password]"
            id="password"
            value="">

    <input
        type="submit"
        value="Create New User">
</form>